// Fetch Invoice
export const FETCH_INVOICE_START = 'FETCH_INVOICE_START';
export const FETCH_INVOICE_SUCCESS = 'FETCH_INVOICE_SUCCESS';
export const FETCH_INVOICE_FAILED = 'FETCH_INVOICE_FAILED';

// Create Invoice
export const CREATE_INVOICE_START = 'CREATE_INVOICE_START';
export const CREATE_INVOICE_SUCCESS = 'CREATE_INVOICE_SUCCESS';
export const CREATE_INVOICE_FAILED = 'CREATE_INVOICE_FAILED';
